name: Test

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'jest.config.ts'
      - 'tsconfig*'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'jest.config.ts'
      - 'tsconfig*'

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: NPM install, lint, build, test
        run: |
          npm i
          npm run test

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
